### PR TITLE
Fix: Terminates if empty line is read.

### PR DESCRIPTION
**Pull request by htgoebel**
This code
https://github.com/DigitaleGesellschaft/Anonip/blob/b0d168ec4a223f70374693ead40a696b6886bc28/anonip.py#L116-L122
will terminate the program if an empty line or a line containing only white-space is read.

I'm not sure whether this behavior was intended since the respective test-case does not actually test this. I added a test-case (2nd commit) for this so one can easily spot the behavior.

IMHO reading an empty or all-white-space line is unusual, but should not terminate the program. The program should only terminate on EOF (or on error).

3rd commit changes the behavior to not terminate in this case and adjusts the test-case so the difference can be spotted easily.

### CODE REVIEW

**Comment by open-dynaMIX** [comment]
Thank you @htgoebel for bringing this up! I agree that we should not terminate on an empty or all-white-space line.

As far as I can see, your [commit](https://github.com/DigitaleGesellschaft/Anonip/pull/10/commits/1f425910e746a3e427e5e63941e947c607d25d67) only handles all-whitespace-lines.

I will look closer into this as soon as I find the time.

**Comment by open-dynaMIX** [comment]
After a very short look at it, maybe we could simplify the whole method into:

```python
    def run(self):
        """
        Generator that reads from stdin and loops forever.

        Yields anonymized log lines.

        :return: None
        """
        for line in sys.stdin:
            line = line.rstrip()

            logger.debug("Got line: {}".format(line))

            yield self.process_line(line)
```

**Comment by htgoebel** [comment]
> As far as I can see, your commit only handles all-whitespace-lines.

Nope, since `readline()` also returns the LF (or whatever the line-ending is). If the `line == ""` EOL is reached.

> After a very short look at it, maybe we could simplify the whole method into:

This is absolutely true.

There is a minor change in behavior, though: IOErrors are not longer logged here. IMHO this is no problem, even if using anonip as a library, since the application can take car of this. (When running anonip as a script, `main()` does this already).

Shall I apply this change, replacing my commit), or will you add another commit?

**Comment by open-dynaMIX** [comment]
> Nope, since readline() also returns the LF (or whatever the line-ending is). If the line == "" EOL is reached.

Ah, you're right!

>There is a minor change in behavior, though: IOErrors are not longer logged here. IMHO this is no problem, even if using anonip as a library, since the application can take car of this. (When running anonip as a script, main() does this already).

I'd say having to handle the IOError is preferable and more transparent when using anonip as a library.

> Shall I apply this change, replacing my commit), or will you add another commit?

Cool, go ahead!

**Comment by open-dynaMIX** [comment]
:100: Thanks a lot!

**Pull request merged**
